### ISSUE TITLE
Irrelevant link on the README page.

### ISSUE THREAD

**Issue by sleyzerzon** [org-tigris-jsapar/jsapar#13]
The link to the Implied Decimal page redirecting to IBM site seems to refer to some unrelated information.  Is it supposed to link [here ](https://www.ibm.com/docs/en/spss-statistics/26.0.0?topic=command-implied-decimal-positions-data-list)instead?

**Comment by stenix71** [comment]
Thank you for pointing that out. I think [this link](http://www.3480-3590-data-conversion.com/article-implied-decimal.html) is even better since it does not reside under some product of a specific version. I will update the readme page.
